### ISSUE TITLE
Writing CipherTextTuple, PrivateKey and PublicParameters to file for later use

### ISSUE THREAD

**Issue by augre** [cryptid-org/cryptid-native#25]
Hi Guys,

I am trying to write the CipherTextTuple, PrivateKey and PublicParameters to file so I can later decrypt the cipherText. 

This is how I'm trying to write them to files and read them back.

The thing is that if I just insert these lines into the example code:

```
    writePublicParToFile(publicParameters);
    writeCipherTextToFile(ciphertext);
    writePrivateKeyToFile(privateKey);

    readCipherTextFromFile(ciphertext);
    readPublicParFromFile(publicParameters);
    readPrivateKeyFromFile(privateKey);
```

Then it works. In the example code it writes everything to file then reads back everything to the same place. But if I just want read the data back from the files and decrypt it doesn't.
here is the entire file:
https://github.com/augre/CryptID_getting_familiar/blob/master/test.c

I suppose I am not writing the whole structs to the files, or something like that. 

Thank you!

**Comment by battila7** [comment]
Hi,

I've examined the source code you've provided above (https://github.com/augre/CryptID_getting_familiar/blob/master/test.c).

Let me explain the issue by putting it into some context. So the thing is, our library currently suffers from leaking implementation. This means, that clients of the library have to deal with types and routines which normally should be an implementation detail only. Here I'm referring to GMP-related stuff. What's the connection between this and your code? Let me continue.

For example, [`AffinePoint`](https://github.com/cryptid-org/cryptid-native/blob/78a50736f3e62aad9ddce073ffa572d20474914a/include/elliptic/AffinePoint.h#L16) (which is the type of the private key) is defined as follows:

~~~C
/**
 * Represents an affine point with coordinates.
 */
typedef struct AffinePoint
{
    /**
     * The \f$x\f$ coordinate.
     */
    mpz_t x;

    /**
     * The \f$y\f$ coordinate.
     */
    mpz_t y;
} AffinePoint;
~~~

As you can see, the *x* and *y* coordinates are typed as `mpz_t`-s. `mpz_t` is, in turn, defined in GMP as follows:

~~~C
typedef struct
{
  int _mp_alloc;		/* Number of *limbs* allocated and pointed
				   to by the _mp_d field.  */
  int _mp_size;			/* abs(_mp_size) is the number of limbs the
				   last field points to.  If _mp_size is
				   negative this is a negative number.  */
  mp_limb_t *_mp_d;		/* Pointer to the limbs.  */
} __mpz_struct;

typedef __mpz_struct mpz_t[1];
~~~

Now, let's connect the dots! When you write

~~~
fwrite(&privateKey, sizeof(struct AffinePoint), 1, fp);
~~~

in your code, you're not actually writing the coordinates of the affine point to the file, but memory addresses. That's why your code breaks, when you're trying to read back from that very same file later: the data is gone, and you're left with memory addresses in the file.

You have to implement a bit of data marshaling yourself as of now (we're going to deal with this problem later, as our current development priorities somewhat differ from library UX). I'd suggest to take a look at [GMP Integer Import and Export](https://gmplib.org/manual/Integer-Import-and-Export.html) as well as the [Interoperability Layer in CryptID.js](https://github.com/cryptid-org/cryptid-js/tree/master/src/native-interop/src) which makes heavy use of import/export (although mostly using strings).

**Comment by augre** [comment]
Thank you very much for the detailed response!

**Comment by augre** [comment]
Hi,
I added these functions here:
https://github.com/augre/cryptid-native/commit/643e2c3e2884d793137de2a520d74d8dce9fc919

It is not the best way of doing it but it seems to work, please let me know if you have any comments.

**Comment by BeardOfDoom** [comment]
Hi @augre 

First of all, you made [Utils.c](https://github.com/augre/cryptid-native/blob/643e2c3e2884d793137de2a520d74d8dce9fc919/src/util/Utils.c) into a 600 line file, which may make it hard to maintain in my opinion. So I suggest you to move the file writer and reader functions into a new file with a meaningful name. 

Secondly, I do not know what is the recommended way to write into files and read back, but I think opening and closing a lot of files may be a slow attempt. You might want to check it. If you did already, please send me the source, so I can learn something new too :)

Thirdly, in [dec_r.c](https://github.com/augre/cryptid-native/blob/643e2c3e2884d793137de2a520d74d8dce9fc919/dec_r.c) the validation part is not right after the `PublicParameters` read. Seems like you doubled the validation. First, you validate every part of it one by one, then you validate them again with the validation of `publicParameters2`. I assume you did it to be able to tell which part was invalid, but it is unnecessary in my opinion.

Finally, we are working on a second version of the library, which will change a lot of things, the structure of the library included. One cool thing for you is issue #44, which will probably make writing into files, then reading back much easier, so you might be able to reduce the complexity of your functions.

**Comment by augre** [comment]
Thanks!

I moved them to util/IO.c.

For the opening and closing problem I found gmp_fprintf and gmp_fscanf this way it is possible to write everything belonging together logically into one file. So it might not be necessary to make more easily serializable and deserializable in #44 .
