### ISSUE TITLE
Help writing PublicParameters HashFunction to file for later use

### ISSUE THREAD

**Issue by augre** [cryptid-org/cryptid-native#29]
Hi,

I'm thinking about how to write and then read back the publicparameters hasfunction to and from file.

This is for the purpose of distributing the public parameters among the clients. Would this be the preferred way of doing it?

```
typedef struct PublicParameters
{
    /**
     * The Type-1 elliptic curve we're operating over. Note, that the {@code p} field of {@code BFPublicParameters}
     * corresponds to {@code ellipticCurve.fieldOrder}.
     */
    EllipticCurve ellipticCurve;

    /**
     * Subgroup order.
     */
    mpz_t q;

    /**
     * A point in \f$E(F_p)\f$.
     */
    AffinePoint pointP;

    /**
     * A point in \f$E(F_p)\f$.
     */
    AffinePoint pointPpublic;

    /**
     * The used hash function.
     */
    HashFunction hashFunction;
} PublicParameters;
```

```
/**
 * Struct holding hash function data.
 */
typedef struct HashFunction
{
    /**
     * Pointer to the actual hash function. The function should take three parameters:
     *   * pointer to the message,
     *   * the length of the message,
     *   * pointer to the result buffer.
     * The return value should be the pointer to the result buffer.
     */
    unsigned char* (*sha_hash)(const unsigned char*, size_t, unsigned char*);

    /**
     * Size of the hash function's output.
     */
    size_t hashLength;
} HashFunction;
```

**Comment by battila7** [comment]
Hi,

of course, when distributins such data, you must write `PublicParameters` out into some persistent target. However, as you've pointed out, currently, it's basically impossible to persist `PublicParameters` since `HashFunction` contains a function pointer.

This is clearly something that we should have thought of (however, our main focus was CryptID.js that did not pose such use cases). Tomorrow we are going to make changes to the public API, that will make it possible to persist and restore variables of type `PublicParameters`.

This modification can be seen as a breaking change, however, as of our current knowledge, given the small number of clients, this does not pose any problems.

Thanks!
Attila

**Comment by battila7** [comment]
This issue is going to be updated once the implementation is merged.

Feel free to either close the issue or continue the conversation then.

Thanks!

**Comment by augre** [comment]
Thank you very much!

**Comment by BeardOfDoom** [comment]
The changes are still not correct, there are some memory leaks, so it is not merged yet.

I will reopen this issue, until the correct reimplementation is merged.

**Comment by BeardOfDoom** [comment]
@augre The new implementation of the hash functions is merged to master.

Please try writing to file and reading it back now. If the fix is good, feel free to close the issue.

**Comment by BeardOfDoom** [comment]
Since there was no further request, I assume the fix was good, so I close the issue.
