### ISSUE TITLE
Compile for Arduino

### ISSUE THREAD

**Issue by augre** [cryptid-org/cryptid-native#58]
Hi Guys,

Do you think it is possible to compile cryptid-native so I could use it from an Arduino? 

If so could you give me some hints/directions?

Thanks!

**Comment by battila7** [comment]
Hi,

I'd like to start by underlining the fact that supporting a use case like this is a non-goal for the library. CryptID.native is intended for WASM compilation mostly.

Putting that aside, I think that you have a great chance porting the library tó Arduino. The library makes little use of the C standard library (mostly, as I recall, memory allocation), so it's not our code that would cause you headaches. The main issue in my opinion is GMP. However, CryptID.native uses only a subset of GMP functions that also happen to be included in smaller scale version of GMP, called mini-gmp.

Summarizing, CryptID.native should be able to run on an Arduino using mini-gmp instead of GMP. Another issue can be the RNG, but CryptID.native also supports the inclusion of a custom RNG:
https://github.com/cryptid-org/cryptid-native/blob/8d972e2526d16e49279bd5b2ce4f50903ed10c44/src/util/RandBytes.c#L15

Please keep in mind though, that I'm not particularly familiar with arduinos, so I might be wrong!

**Comment by battila7** [comment]
@BeardOfDoom Should we support mini-gmp out of the box? It should be doable.

**Comment by BeardOfDoom** [comment]
Will take a look on that.

**Comment by augre** [comment]
How about Node.js v8+? what is that used for?

**Comment by BeardOfDoom** [comment]
Node is only used for Task, which helps with building and testing the library, it is not obligatory to use, furthermore we are planning to get rid of it and use cmake instead as you can see in issue #43.

#protip right now you can run the task.sh on deskrop and copy the build scripts which it executes, so you really don't need to deal with Node on arduino.

**Comment by BeardOfDoom** [comment]
@augre I checked if the library works with mini-gmp and it works fine with the code I included in #63, so you might want to try using it on arduino (I have no idea if it works on arduino or not). 

Right now as I mentioned in the pull request, we don't have a switchable build script so I added static defines in the code, like you can see in the gmp.h. So keep that in mind while you are trying to work with it on arduino.

**Comment by augre** [comment]
Than you very much! I will try it.

**Comment by BeardOfDoom** [comment]
@augre were you able to take a step forward in this direction? If yes, please inform us if this issue is outdated or not.

**Comment by augre** [comment]
@BeardOfDoom I got stuck with this.

I was trying to use https://github.com/a9183756-gh/Arduino-CMake-Toolchain to compile and build for arduino but couldn't get it working. 


> #protip right now you can run the task.sh on deskrop and copy the build scripts which it executes, so you really don't need to deal with Node on arduino.

I didn't understand how I could use the build scripts could you please explain this?

Thanks!

**Comment by BeardOfDoom** [comment]
I am sorry, I'm not familiar with arduino at all. I thought you could run gcc command to compile our library and somehow attach it to an arduino binary. That way you could dump the gcc command with our node script, but it might not be the case as I see.

**Comment by augre** [comment]
Hi,

It seems like I could compile it with the Arduino IDE. It was actually a lot simpler than I thought, I will share it after testing.
